name: build and linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: make install
      - name: run linter
        run: make lint
      - name: run build
        run: make start
